baseURL: http://thalis.netlify.app/
title: Thalis Rebouças
languageCode: pt-br
googleAnalytics: 'G-HQXYFWMZ3J'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

permalinks:
  post: /:year/:month/:day/:slug/

params:
  author: Thalis
  plugins:
     css:
       - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
       - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
       - link: plugins/github.css
       - link: plugins/css/reset.css
       - link: plugins/css/plugins.css
       - link: plugins/css/style.css
       - link: plugins/css/color.css

     js:
      - link: plugins/js/jquery.min.js
      - link: plugins/js/plugins.js
      - link: plugins/js/scripts.js
      - link: //cdnjs.cloudflare.com/ajax/libs/validate.js/0.13.1/validate.min.js
      - link: plugins/js/highlight.pack.js
     MathJaxVersion: 2.7.5
     highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
     highlightjsLang:
      - "r"
      - "yaml"
     highlightjsTheme: "github"
     highlightjsVersion: 10.5.0 
