baseURL: https://thalisreboucas.com.br/
title: Thalis Rebouças
languageCode: pt-br
googleAnalytics: 'G-HQXYFWMZ3J'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
markup:
  goldmark:
    renderer:
      unsafe: yes

permalinks:
  post: /:year/:month/:day/:slug/

params:
  author: Thalis
  favicon: images/favicon.ico
  logo2: images/logo2.png
  logo: images/logo.png
  pg404: images/bg/16.jpg
  plugins:
     css:
       - link: https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap
       - link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css
       - link: plugins/css/github.css
       - link: plugins/css/reset.css
       - link: plugins/css/plugins.css
       - link: plugins/css/style.css
       - link: plugins/css/table.css
       - link: plugins/css/color.css
     js:
      - link: plugins/js/jquery.min.js
      - link: plugins/js/plugins.js
      - link: plugins/js/scripts.js
      - link: //cdnjs.cloudflare.com/ajax/libs/validate.js/0.13.1/validate.min.js
      - link: plugins/js/highlight.pack.js
     MathJaxVersion: 2.7.5
     highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
     highlightjsLang:
      - "r"
      - "yaml"
     highlightjsTheme: "github"
     highlightjsVersion: 10.5.0 


menu:
       main:
        - name: Home
          url: /
          weight: 1
        - name: Sobre Mim
          pre: '#'
          url: sec2
          weight: 2
        - name: Resumo
          pre: '#'
          url: sec3
          weight: 3
        - name: Blog
          url: post
          weight: 4
        - name: Contato
          pre: '#'
          url: sec6
          weight: 5
